### ISSUE TITLE
fasthttp: Host request-header not being passed correctly

### ISSUE THREAD

**Issue by wahmedswl** [codesenberg/bombardier#17]
Hi, i am running bombardier against Linkerd Service, curl works fine but requests with bombardier resulting in 5xx

```
curl -H "Host: hello" localhost:4140
Hello linkerd!
```

```
bombardier -c 125 -n 10000 -H "Host: hello" localhost:4140
Bombarding http://localhost:4140 with 10000 requests using 125 connections
 10000 / 10000 [===================================================================================================================================================================] 100.00% 6s Done!
Statistics        Avg      Stdev        Max
  Reqs/sec      1578.00     682.09       4384
  Latency       81.62ms    96.82ms      1.74s
  HTTP codes:
    1xx - 0, 2xx - 0, 3xx - 0, 4xx - 0, 5xx - 10000
    others - 0
  Throughput:   624.13KB/s
```

Any help would be appreciated. Thanks

**Comment by codesenberg** [comment]
I've done some research on this topic. From what I've found it looks like there is no way to set *Host* header with *fasthttp* and we're not gonna get any help from the authors, since the library is pretty much abandonded. The good news though is that after I land #15 you will be able to workaround this issue by using *net/http*(`--http1`/`--http2` flags). #15 will probably land in the first half of May. Until then you'll have to wait or use some other tool, sorry.

**Comment by codesenberg** [comment]
@wahmedswl, if you can build **bombardier** from source this should already be working. And here's a patch for [hey](https://github.com/rakyll/hey) if you want to compare the two:
```diff
diff --git a/requester/requester.go b/requester/requester.go
index 593cbaf..1f6c65b 100644
--- a/requester/requester.go
+++ b/requester/requester.go
@@ -178,6 +178,9 @@ func (b *Work) makeRequest(c *http.Client) {
                }
                req = req.WithContext(httptrace.WithClientTrace(req.Context(), trace))
        }
+       if host := req.Header.Get("Host"); host != "" {
+               req.Host = host
+       }
        resp, err := c.Do(req)
        if err == nil {
                size = resp.ContentLength
```
