### ISSUE TITLE
System requirements

### ISSUE THREAD

**Issue by cyantarek** [codesenberg/bombardier#37]
How much system resource(CPU, RAM, storage, bandwidth etc.) I need to spawn 2 millions concurrent users?

**Comment by codesenberg** [comment]
Hmm... it's hard to tell. Depending on how much those 2 million users do. In any case, I think this task will require at least several machines, since 2 million concurrent users is a huge number. First, you've gotta find out how many users you can "spawn" on one machine using trial & error. This will depend on how many requests your typical user sends and how heavy those requests are. It will also depend on which client you chose. `fasthttp` uses less memory, so you should probably use it, unless the server/application you are testing refuses to work with it (in my practice, some apps haven't worked with `fasthttp`, so, I added `net/http`). It's reasonable to assume that one machine can establish at least 5000 to 15000 concurrent connections (or maybe more), but this is all I've got for you.
