### ISSUE TITLE
i/o timeout with fasthttp client

### ISSUE THREAD

**Issue by n0madic** [codesenberg/bombardier#38]
There are problems connecting with [envoy](https://github.com/envoyproxy/envoy) proxy

### What version of bombardier are you using?
`bombardier version v1.2`

### What operating system and processor architecture are you using (if relevant)?
`linux/amd64`

### What did you do?

`docker run --rm -d -p 10000:10000 envoyproxy/envoy:latest`
```
$ curl -I http://localhost:10000
HTTP/1.1 200 OK
...
```
```
$ bombardier http://localhost:10000
Statistics        Avg      Stdev        Max
  Reqs/sec         9.45     210.84    4724.01
  Latency        10.01s     3.58ms     10.01s
  HTTP codes:
    1xx - 0, 2xx - 0, 3xx - 0, 4xx - 0, 5xx - 0
    others - 125
  Errors:
    read tcp [::1]:9050->[::1]:10000: i/o timeout - 1
    read tcp [::1]:9248->[::1]:10000: i/o timeout - 1
    read tcp [::1]:9258->[::1]:10000: i/o timeout - 1
    read tcp [::1]:9004->[::1]:10000: i/o timeout - 1
...
```
With net/http client all ok
```
$ bombardier --http1 http://localhost:10000
Statistics        Avg      Stdev        Max
  Reqs/sec       335.52     128.07     750.00
  Latency      365.64ms    86.23ms   565.60ms
  HTTP codes:
    1xx - 0, 2xx - 0, 3xx - 3479, 4xx - 0, 5xx - 0
    others - 0
  Throughput:   308.91KB/s
```
### What you expected to happen?
A typical http connection

### What actually happened?
`read tcp [::1]:9004->[::1]:10000: i/o timeout - 1`

**Comment by n0madic** [comment]
And this is not a fasthttp library problem..
A simple client connects without errors:
```go
package main

import (
    "fmt"
    "os"
    "github.com/valyala/fasthttp"
)

func main() {
	url := os.Args[1]

	client := &fasthttp.Client{}
	request := fasthttp.AcquireRequest()
	response := fasthttp.AcquireResponse()

	defer fasthttp.ReleaseRequest(request)
	defer fasthttp.ReleaseResponse(response)

	request.SetConnectionClose()
	request.SetRequestURI(url)

	if err := client.Do(request, response); err != nil {
		fmt.Println(err)
	} else {
                fmt.Println(string(response.Header.Header()))
	}
}
```
```
$ ./fasthttp http://localhost:10000/test
HTTP/1.1 200 OK
Server: envoy
...
```

**Comment by codesenberg** [comment]
Thanks for your thorough report. I figured out that the culprit of this issue is [this line](https://github.com/codesenberg/bombardier/blob/v1.2/clients.go#L55). `envoy` is probably not very excited about `fasthttp` giving it non RFC-compliant request or something like that.
Now, I'm not sure what would be the best course to resolve this. We could enable headers normalization again (and this is default behaviour of `fasthttp`, that's the reason you're not seeing problems with your snippet). Another possibility would be to provide some flag like `--normalize-headers` or something like this, which I would like to avoid, since there are plenty already.

**Comment by n0madic** [comment]
Why not leave DisableHeaderNamesNormalizing by default?

**Comment by codesenberg** [comment]
Well, `fasthttp` were known for not caring about RFCs much (not sure how things are now). This is why some servers are not happy with it.
Maybe, you got it wrong. It's not like `bombardier` makes non RFC-compliant requests on purpose, it's `fasthttp` that sends "bad" requests if header normalization is off. Initially, I disabled it, because I thought it would allow for more flexibility or something like that.

**Comment by n0madic** [comment]
So can you make DisableHeaderNamesNormalizing by default?
You can only enable it if the --header option is specified..

**Comment by n0madic** [comment]
hmm, in this option enabled my code still works ...
```
$ go run fasthttp.go http://localhost:10000
HTTP/1.1 302 Found
Date: Wed, 05 Sep 2018 06:49:04 GMT
Content-Type: text/plain; charset=utf-8
Content-Length: 327
location: https://www.google.com/sorry/index?continue=https://www.google.com/&q=EgRbxTGlGOD4vdwFIhkA8aeDSyCoapYu8R4SziAjHYL5StE2_AVKMgFy
date: Wed, 05 Sep 2018 06:49:04 GMT
pragma: no-cache
expires: Fri, 01 Jan 1990 00:00:00 GMT
cache-control: no-store, no-cache, must-revalidate
content-type: text/html; charset=UTF-8
server: envoy
content-length: 327
x-xss-protection: 1; mode=block
alt-svc: quic=":443"; ma=2592000; v="44,43,39,35"
x-envoy-upstream-service-time: 261
connection: close
Connection: close
```
Only duplicated headers due to normalization ...

**Comment by codesenberg** [comment]
I dug a bit and it seems like this option affects how `fasthttp` parses response headers. It gets read timeout, because it identifies request's `transfer-encoding` incorrectly. It thinks that this is just a regular response and parses it like one, but it's `chunked`, so, it thinks that there is more to come, while the request is finished. I'm not sure where RFCs stand here, but I think headers should be treated in a case-insensitive manner. It sure looks like a bug on a `fasthttp` side.

**Comment by n0madic** [comment]
better you :)

**Comment by codesenberg** [comment]
@n0madic the issue was fixed. I updated vendored version of `fasthttp` and now it should work as expected. Close this issue if the fix is working for you.

**Comment by n0madic** [comment]
Good job, thank you
